/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MappingChar123IdChar125RouteImport } from './routes/mapping{-$id}'
import { Route as ImportChar123idChar125RouteImport } from './routes/import-{$id}'
import { Route as ImportsRouteImport } from './routes/Imports'
import { Route as IndexRouteImport } from './routes/index'

const MappingChar123IdChar125Route = MappingChar123IdChar125RouteImport.update({
  id: '/mapping{-$id}',
  path: '/mapping{-$id}',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportChar123idChar125Route = ImportChar123idChar125RouteImport.update({
  id: '/import-{$id}',
  path: '/import-{$id}',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsRoute = ImportsRouteImport.update({
  id: '/Imports',
  path: '/Imports',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Imports': typeof ImportsRoute
  '/import-{$id}': typeof ImportChar123idChar125Route
  '/mapping{-$id}': typeof MappingChar123IdChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Imports': typeof ImportsRoute
  '/import-{$id}': typeof ImportChar123idChar125Route
  '/mapping{-$id}': typeof MappingChar123IdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Imports': typeof ImportsRoute
  '/import-{$id}': typeof ImportChar123idChar125Route
  '/mapping{-$id}': typeof MappingChar123IdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Imports' | '/import-{$id}' | '/mapping{-$id}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Imports' | '/import-{$id}' | '/mapping{-$id}'
  id: '__root__' | '/' | '/Imports' | '/import-{$id}' | '/mapping{-$id}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportsRoute: typeof ImportsRoute
  ImportChar123idChar125Route: typeof ImportChar123idChar125Route
  MappingChar123IdChar125Route: typeof MappingChar123IdChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mapping{-$id}': {
      id: '/mapping{-$id}'
      path: '/mapping{-$id}'
      fullPath: '/mapping{-$id}'
      preLoaderRoute: typeof MappingChar123IdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-{$id}': {
      id: '/import-{$id}'
      path: '/import-{$id}'
      fullPath: '/import-{$id}'
      preLoaderRoute: typeof ImportChar123idChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Imports': {
      id: '/Imports'
      path: '/Imports'
      fullPath: '/Imports'
      preLoaderRoute: typeof ImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportsRoute: ImportsRoute,
  ImportChar123idChar125Route: ImportChar123idChar125Route,
  MappingChar123IdChar125Route: MappingChar123IdChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
